# Generated by Django 4.2.2 on 2023-06-27 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecoDinerApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarbonFootprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "energy_consumption",
                    models.DecimalField(decimal_places=2, default="", max_digits=10),
                ),
                (
                    "water_consumption",
                    models.DecimalField(decimal_places=2, default="", max_digits=10),
                ),
                (
                    "waste_production",
                    models.DecimalField(decimal_places=2, default="", max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resources", models.TextField(default="")),
                ("engagement_tools", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="SustainableMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ingredients", models.TextField(default="")),
                ("nutritional_analysis", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="WasteReduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("waste_management", models.TextField(default="")),
                ("inventory_management", models.TextField(default="")),
            ],
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="carbon_footprint",
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="location",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="owner",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.DeleteModel(
            name="Menu",
        ),
        migrations.AddField(
            model_name="wastereduction",
            name="restaurant",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="ecoDinerApp.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="sustainablemenu",
            name="restaurant",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="ecoDinerApp.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="employeetraining",
            name="restaurant",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="ecoDinerApp.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="carbonfootprint",
            name="restaurant",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="ecoDinerApp.restaurant",
            ),
        ),
    ]
