# Generated by Django 4.2.2 on 2023-06-27 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "ecoDinerApp",
            "0002_carbonfootprint_employeetraining_sustainablemenu_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="carbonfootprint",
            name="energy_consumption",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="carbonfootprint",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ecoDinerApp.restaurant"
            ),
        ),
        migrations.AlterField(
            model_name="carbonfootprint",
            name="waste_production",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="carbonfootprint",
            name="water_consumption",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="employeetraining",
            name="engagement_tools",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="employeetraining",
            name="resources",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="employeetraining",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ecoDinerApp.restaurant"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="sustainablemenu",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ecoDinerApp.restaurant"
            ),
        ),
        migrations.AlterField(
            model_name="wastereduction",
            name="inventory_management",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="wastereduction",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ecoDinerApp.restaurant"
            ),
        ),
        migrations.AlterField(
            model_name="wastereduction",
            name="waste_management",
            field=models.TextField(),
        ),
    ]
